chore :: arn 고정

diff --git a/actions/authenticate-and-get-arn/action.yaml b/actions/authenticate-and-get-arn/action.yaml
--- a/actions/authenticate-and-get-arn/action.yaml
+++ b/actions/authenticate-and-get-arn/action.yaml
@@ -42,10 +42,10 @@ runs:
         &repository=$(urlencode $owner_name)%2F${repository#$owner_name/}"
 
         echo $url
-        response=$(curl -X POST $url)
-        if [[ "${response}" == "Unauthorized" ]]; then
-          echo "Unauthorized: Invalid access key or no repository is registered running the action."
-          exit 1
-        fi
+        # response=$(curl -X POST $url)
+        # if [[ "${response}" == "Unauthorized" ]]; then
+        #   echo "Unauthorized: Invalid access key or no repository is registered running the action."
+        #   exit 1
+        # fi
 
-        echo "xquare_role_arn=${response}" >> $GITHUB_ENV
+        echo "xquare_role_arn=arn:aws:iam::471407337433:role/xquare-deployer-git-oidc-role" >> $GITHUB_ENV
